language: java
dist: trusty
sudo: false

jdk:
- openjdk8
- oraclejdk8
- openjdk11

cache:
  directories:
  - $HOME/.m2/repository

install:
- cmake --version
- git submodule init
- git submodule update

script:
- mvn -Pcore-test clean install
- cmake .
- ctest .
