language: java

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2/repository

install:
- cmake --version
- git submodule init
- git submodule update

script:
- mvn -Pcore-test clean install
- cmake .
- ctest .
